name: BedwarsAddon
version: ${project.version}
main: spigot.greg.bwaddon.BwAddon
authors: [PuRe_Greg, Misat11]
depend: [BedWars]
api-version: 1.13
commands:
  jointournamentround:
    description: Joins you to the round
    usage: /jointournamentround

