name: BedwarsAddon
version: ${project.version}
main: spigot.greg.bwaddon.BwAddon
authors: [PuRe_Greg]
depend: [Bedwars]
commands:
  customshopgui:
        description: OpenscustomShop
        usage: /customshopgui
        permission: tournament
        permission-message: HEY!, Sorry but you Havnt got Permission to do this Yet!

